# This compose file will start 2 containers: registry and redis.
# registry container will listen on host port 5000, 
# and depend on the redis container as the cache scheme.
registry:
    image: registry:latest
    cpu_shares: 10
    hostname: docker-registry
    mem_limit: 2048m
    ports:
        - "80:5000"
    command:
      ["serve", "/etc/registry/config.yml"]
    privileged: false
    restart: always
    user: root
    volumes:
        - /opt/data/registry:/var/lib/registry
        - ./config.yml:/etc/registry/config.yml
    dns:
        - 114.114.114.114
